# -*- coding: utf-8 -*-
"""Lista_Python_1.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1cBn8Aep6oYThAGzAqgrvqBY5OPDyK1NG

#1º Lista de Exercícios de Python

Como deve ser enviada:


*   O notebook precisa ser todo respondido e executado.
*   O arquivo deve ser baixado em formato .ipynb
*   Após isso deve ser enviado no grupo do Telegram com as seguintes características:
> * Nome do Arquivo: **Lista_Python_1.ipynb**
> * O seu **nome completo, sem abreviações** deve ser colocado como mensagem junto ao arquivo.
> *  Após o nome colocar **#listapython1**

Se essas regras não forem seguidas e o arquivo não for achado, o aluno não será pontuado.

O prazo será informado em sala.

1. Faça um Programa que mostre a mensagem "Alô mundo!" na tela.
"""

print ("Alô mundo!")

"""2. Faça um Programa que peça um número e então mostre a mensagem `"O número informado foi
[número]”`.
"""

numero = input("Declare um número = ")
print ("O número informado foi = ", numero)

"""3. Faça um Programa que peça dois números e imprima a soma."""

x = int(input("Declare o valor de x = "))
y = int(input("Declare o valor de y = "))
print("x + y = ", x + y)

"""4. Faça um Programa que receba 4 notas e mostre a média."""

nota_1 = float(input("A primeira nota é = "))
nota_2 = float(input("A segunda nota é = "))
nota_3 = float(input("A terceira nota é = "))
nota_4 = float(input("A quarta nota é = "))
print ("A média obtida foi", (nota_1 + nota_2 + nota_3 + nota_4) / 4)

"""5. Faça um Programa que converta metros para centímetros."""

Metros = float(input("Digite a quantidade em metros = "))
print ("Convertendo para centimetros ficaria = ", Metros * 100)

"""6. Faça um Programa que peça o raio de um círculo, calcule e mostre sua área. Fórmula: `A = π * r²`"""

Raio = float(input("O valor do raio do circulo é = "))
PI = 3.14
print ("A área do raio é = ", PI * Raio**2 )

"""7. Faça um Programa que calcule a área de um quadrado, em seguida mostre o dobro desta
área para o usuário.
"""

lado_quadrado = float(input("O valor do lado do quadrado é = "))
area_quadrado = lado_quadrado **2
print ("A area do quadrado é = ", area_quadrado)
print ("O dobro da area do quadrado seria = ", area_quadrado *2)

"""8. Faça um Programa que calcule a área de um retângulo, em seguida mostre o dobro desta
área para o usuário.
"""

base_retangulo = float(input("Digite o valor da base do retangulo = "))
altura_retangulo = float(input("Digite o valor da altura do retangulo = "))
print ("A area do retangulo é =", base_retangulo * altura_retangulo )
print ("O dobro da area do retangulo é =", base_retangulo * altura_retangulo * 2)

"""9. Faça um Programa que pergunte quanto você ganha por hora e o número de horas
trabalhadas no mês. Calcule e mostre o total do seu salário no referido mês.
"""

ganho_hr = float(input("Quando vc ganha p/ hr ? "))
trabalho_hr = float(input("Quantas hrs trabalhadas vc tem no mês ? "))
print (f"Você receberá", ganho_hr * trabalho_hr,"reais, nesse mês. ")

"""10. Faça um programa que receba uma lista com NOME, IDADE e ESCOLARIDADE. Após isso, imprima cada um dos itens da lista em um Print diferente utilizando o seu índice na lista."""

lista = [input("Seu nome é : "), input("Sua idade é : "), input("Sua escolaridade é : ")]
print ("Nome :", lista[0])
print ("Idade :",lista[1])
print ("Escolaridade :",lista[2])